### ISSUE TITLE
Method with @Transactional and where query with local variable causes exception

### ISSUE THREAD

**Issue by erichelgeson** [apache/grails-core#11464]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a Transactional method
1. have a local variable the same name as one to be used in the where query
1. use the where {}

### Expected Behaviour

No exception 

### Actual Behaviour

```
2020-01-16 15:38:37.848 ERROR --- [nio-8080-exec-1] o.g.web.errors.GrailsExceptionResolver   : MissingMethodException occurred when processing request: [GET] /test/fails
No signature of method: davetestentity.Friend.call() is applicable for argument types: (davetestentity.TestController$__tt__fails_closure4$_closure6) values: [davetestentity.TestController$__tt__fails_closure4$_closure6@7b857f2b]
Possible solutions: wait(), last(), save(), any(), getAll(), wait(long). Stacktrace follows:

java.lang.reflect.InvocationTargetException: null
	at org.grails.core.DefaultGrailsControllerClass$ReflectionInvoker.invoke(DefaultGrailsControllerClass.java:211)
	at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:188)
	at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
	at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: groovy.lang.MissingMethodException: No signature of method: davetestentity.Friend.call() is applicable for argument types: (davetestentity.TestController$__tt__fails_closure4$_closure6) values: [davetestentity.TestController$__tt__fails_closure4$_closure6@7b857f2b]
Possible solutions: wait(), last(), save(), any(), getAll(), wait(long)
	at org.grails.datastore.gorm.query.criteria.AbstractDetachedCriteria.build(AbstractDetachedCriteria.groovy:821)
	at grails.gorm.DetachedCriteria.build(DetachedCriteria.groovy:583)
	at org.grails.datastore.gorm.GormStaticApi.where(GormStaticApi.groovy:194)
	at org.grails.datastore.gorm.GormEntity$Trait$Helper.where(GormEntity.groovy:438)
	at davetestentity.TestController.$tt__fails(TestController.groovy:30)
	at grails.gorm.transactions.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:94)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at grails.gorm.transactions.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:91)
	... 13 common frames omitted
```

NOTE: Removing the @Transactional from the method allows the where query to behave correctly.

### Environment Information

- **Operating System**: osx
- **Grails Version:** 4.0.1
- **JDK Version:** 1.8.222
- **Container Version (If Applicable):** n/a

### Example Application

- https://github.com/erichelgeson/whereQueryFail/blob/master/grails-app/controllers/davetestentity/TestController.groovy#L23

**Comment by erichelgeson** [comment]
https://gist.github.com/erichelgeson/e2673f88dc4e5fa55afef028c518952c/revisions?diff=unified

Seems the closure generation when @Transactional is on does not keep the getFriend

**Comment by erichelgeson** [comment]
This does work.
```groovy
    @Transactional // works
    def index() {
        def friend = Friend.first()
        def users
        Friend tmpFriend = friend
        Closure c = { // <--- Explicitly define the closure outside where
            friend.id == tmpFriend.id
        }
        if (friend) {
            users = User.where(c).list()
        }
        render users as JSON
    }
```
It seems to be the @Transactional + where closure code generation is causing the wrong output.

**Comment by davydotcom** [comment]
this is a really weird regression issue that has been stopping us from moving up to grails4+ . We have found a workaround but its a very large project id rather not have to inject across the board.

**Comment by davydotcom** [comment]
correction... no known workaround exists and this seems like a major issue for GORM in general.

**Comment by erichelgeson** [comment]
If you use `@Transactional` (which you must start using due to hibernate 5.2+) and want to us `where` queries:

* LHS can not share a name with a local variable in the method
* LHS can not share a name with a class getter/property (eg: `account` if you have an account helper trait) 
* LHS can not share a name with `Closure` variable/getter (eg: `owner`, etc)
* LHS can not be quoted (note: you can without the annotation)

I've attempted to debut the `TransactionalTransform` but am not experienced enough with AST's to see the but where the it goes wrong.

Really the only work around is to not use Transactional and where together.

**Comment by davydotcom** [comment]
Started seeing this start shortly after grails 3.3.9 btw.

**Comment by davydotcom** [comment]
confirmed groovy 2.4.15 on both builds between 3.3.9 and 3.3.10

**Comment by bdwheeler** [comment]
traced this - in 
`protected MethodNode moveOriginalCodeToNewMethod(MethodNode methodNode, String renamedMethodName, Parameter[] newParameters, ClassNode classNode, SourceUnit source, Map<String, ClassNode> genericsSpec) {
...
VariableScopeVisitor scopeVisitor = new VariableScopeVisitor(new SourceUnit("dummy", "dummy", source.getConfiguration(), source.getClassLoader(), new ErrorCollector(source.getConfiguration())))

        if (methodNode == null) {
            scopeVisitor.visitClass(classNode)
        } else {
            scopeVisitor.prepareVisit(classNode)
            scopeVisitor.visitMethod(renamedMethodNode)
        }
...
`
In the failed case - this is our method expression
`org.codehaus.groovy.ast.expr.MethodCallExpression@d9f41[object: org.codehaus.groovy.ast.expr.VariableExpression@d9f41[variable: delegate] method: ConstantExpression[friend] arguments: org.codehaus.groovy.ast.expr.ArgumentListExpression@d9f41[org.codehaus.groovy.ast.expr.ClosureExpression@d9f41[]{ org.codehaus.groovy.ast.stmt.BlockStatement@d9f41[org.codehaus.groovy.ast.stmt.ExpressionStatement@d9f41[expression:org.codehaus.groovy.ast.expr.MethodCallExpression@d9f41[object: org.codehaus.groovy.ast.expr.VariableExpression@d9f41[variable: this] method: ConstantExpression[eq] arguments: org.codehaus.groovy.ast.expr.ArgumentListExpression@d9f41[ConstantExpression[id], org.codehaus.groovy.ast.expr.PropertyExpression@15d157[object: org.codehaus.groovy.ast.expr.VariableExpression@15d023[variable: friend] property: ConstantExpression[id]]]]]] }]]
`

In groovy VariableScopeVisitor
`public void visitMethodCallExpression(MethodCallExpression call) {
        if (call.isImplicitThis() && call.getMethod() instanceof ConstantExpression) {
            ConstantExpression methodNameConstant = (ConstantExpression) call.getMethod();
            Object value = methodNameConstant.getText();

            if (!(value instanceof String)) {
                throw new GroovyBugError("tried to make a method call with a non-String constant method name.");
            }

            String methodName = (String) value;
            Variable v = checkVariableNameForDeclaration(methodName, call);
            if (v != null && !(v instanceof DynamicVariable)) {
                checkVariableContextAccess(v, call);
            }

            if (v instanceof VariableExpression || v instanceof Parameter) {
                VariableExpression object = new VariableExpression(v);
                object.setSourcePosition(methodNameConstant);
                call.setObjectExpression(object);
                ConstantExpression method = new ConstantExpression("call");
                method.setSourcePosition(methodNameConstant); // important for GROOVY-4344
                call.setImplicitThis(false);
                call.setMethod(method);
            }

        }
        super.visitMethodCallExpression(call);
    }
`
In MethodCallExpression - implicitThis is always set to true in the constructor so this if statement will kick in on a method call with a ConstantExpression method.
You can see in this case the expression is "delegate".  The groovy test cases this is usually "this".
In the checkVariableNameForDeclaration call - the scope is walked up looking for the variable - in our case "friend".
Friend is found 2 scopes up in the method call - and is a VariableExpression - so it triggers the changing of "delegate.friend" into "friend.call" - which is not valid and results in a no such method exception.

In our working example the checkVariableNameForDeclaration call the variable friend is not found because it does not conflict and the response is a DynamicVariable - which prevents the code from falling into the "call" swap out and thus working.

I doubt this is the right 'fix' - but if I change the if statement to check the method for 'this' explicitly - then the test cases pass, and it solves this situation.  I am figuring that MethodCallExpression should properly figure out when to set implicitThis = true or not - or maybe enhance the logic around when to swap a method call into a '.call' here.

`Boolean isThisCall = (call.getObjectExpression() instanceof VariableExpression && ((VariableExpression)call.getObjectExpression()).getName() == "this");
        if (isThisCall && call.getMethod() instanceof ConstantExpression) {
        //if (call.isImplicitThis() && call.getMethod() instanceof ConstantExpression) {
`

Here is a screenshot of transformed code with the fix:
https://bertram.d.pr/49lTZd

**Comment by erichelgeson** [comment]
Added these details and created a Groovy ticket https://issues.apache.org/jira/browse/GROOVY-9629
