### ISSUE TITLE
Deploy grails 4 on tomcat

### ISSUE THREAD

**Issue by jostheron** [apache/grails-core#11511]
I created an empty grails 4.0.2 project, using "grails create-app testbot"

I then built a war file using 'grails war' and copied it to the webapps directory of a tomcat 9.0.16 and 9.0.24 running on ubuntu. When the app starts up I get the below errors and the app doesn't start. This works fine on windows using 'grails run-app' and deploying it to a tomcat 9.0.33 instance on windows. I also tried building it with grails assemble and no luck.

i've tried changing compile to provided in build.gradle ->  for "org.springframework.boot:spring-boot-starter-tomcat" and I un-commented it all together but the issue remains for both these test cases.

29-Mar-2020 21:57:39.308 SEVERE [Catalina-utility-2] org.apache.catalina.startup.HostConfig.deployWAR Error deploying web application archive [/var/lib/tomcat9/webapps/testbot-0.1.war] java.lang.IllegalStateException: Error starting child at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:720) at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690) at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705) at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:978) at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1849) at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118) at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:773) at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:427) at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1620) at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:305) at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123) at org.apache.catalina.core.ContainerBase.backgroundProcess(ContainerBase.java:1151) at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1353) at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1357) at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1335) at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.base/java.lang.Thread.run(Thread.java:834) Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/testbot-0.1]] at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:440) at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:198) at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:717) ... 24 more Caused by: java.lang.NoSuchMethodError: 'java.lang.String org.codehaus.groovy.runtime.DefaultGroovyMethods.join(java.lang.Iterable, java.lang.String)' at org.grails.config.NavigableMap.(NavigableMap.groovy:38) at org.grails.config.NavigableMap.mergeMapEntry(NavigableMap.groovy:238) at org.grails.config.NavigableMap.mergeMapEntry(NavigableMap.groovy) at org.grails.config.NavigableMap.mergeMaps(NavigableMap.groovy:149) at org.grails.config.NavigableMap.merge(NavigableMap.groovy:125) at org.grails.config.NavigableMap.merge(NavigableMap.groovy) at grails.util.Metadata.loadYml(Metadata.groovy:177) at grails.util.Metadata.access$0(Metadata.groovy) at grails.util.Metadata$_loadFromDefault_closure2.doCall(Metadata.groovy:129) at grails.util.Metadata$_loadFromDefault_closure2.call(Metadata.groovy) at org.codehaus.groovy.runtime.IOGroovyMethods.withStream(IOGroovyMethods.java:1160) at org.codehaus.groovy.runtime.ResourceGroovyMethods.withInputStream(ResourceGroovyMethods.java:1570) at grails.util.Metadata.loadFromDefault(Metadata.groovy:128) at grails.util.Metadata.(Metadata.groovy:58) at grails.util.Metadata.getCurrent(Metadata.groovy:114) at grails.util.Environment.resolveCurrentEnvironment(Environment.java:295) at grails.util.Environment.cacheCurrentEnvironment(Environment.java:321) at grails.util.Environment.getCurrent(Environment.java:288) at grails.util.Environment.(Environment.java:132) at java.base/java.lang.Class.forName0(Native Method) at java.base/java.lang.Class.forName(Class.java:398) at org.codehaus.groovy.runtime.callsite.CallSiteArray$1.run(CallSiteArray.java:65) at org.codehaus.groovy.runtime.callsite.CallSiteArray$1.run(CallSiteArray.java:62) at java.base/java.security.AccessController.doPrivileged(Native Method) at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallStaticSite(CallSiteArray.java:62) at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallSite(CallSiteArray.java:159) at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112) at Script1.run(Script1.groovy:26) at Script1$run.call(Unknown Source) at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112) at ch.qos.logback.classic.gaffer.GafferConfigurator.run(GafferConfigurator.groovy:77) at ch.qos.logback.classic.gaffer.GafferConfigurator$run.callCurrent(Unknown Source) at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133) at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141) at ch.qos.logback.classic.gaffer.GafferConfigurator.run(GafferConfigurator.groovy:44) at ch.qos.logback.classic.gaffer.GafferUtil.runGafferConfiguratorOn(GafferUtil.java:43) at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:67) at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150) at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84) at org.slf4j.impl.StaticLoggerBinder.(StaticLoggerBinder.java:55) at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150) at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124) at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:417) at ch.qos.logback.classic.util.StatusViaSLF4JLoggerFactory.addStatus(StatusViaSLF4JLoggerFactory.java:32) at ch.qos.logback.classic.util.StatusViaSLF4JLoggerFactory.addInfo(StatusViaSLF4JLoggerFactory.java:20) at ch.qos.logback.classic.servlet.LogbackServletContainerInitializer.onStartup(LogbackServletContainerInitializer.java:32) at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5135) at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ... 25 more 29-Mar-2020 21:57:39.309 INFO [Catalina-utility-2]

**Comment by jjelliott** [comment]
The Grails Cache plugin which is installed by default is incompatible with the newer Groovy version used in Grails 4.0.2 and newer.

Either remove the dependency or exclude the `groovy-all` dependency.
```groovy
compile "org.grails.plugins:cache", {
    exclude group: "org.codehaus.groovy", module: "groovy-all"
}
```

Note: I have no idea how functional the cache plugin is if you just exclude the dependency.

**Comment by jostheron** [comment]
Thank you! Solved it.

**Comment by puneetbehl** [comment]
@jostheron I tried to replicate the problem by creating a Grails 4.0.2 web application and then deploying the WAR created with `./grailsw war` command to the Tomcat 9.0.22 but I am unable to see the above exception. 

It is definitely an issue with the Groovy version mismatch. I think it should be transferred to the Grails cache plugin repository. In any case, it would be good to have a way to replicate the problem.

**Comment by rgogulakrishnan** [comment]
I too got this error and found that cache plugin pulled groovy-all 2.1.9. Excluding that resolved the issue. Used grails 4.0.3 version.

**Comment by olliefreeman** [comment]
Had the same issue using Grails 4.0.3 but applying the exclude seems to have solved it

**Comment by ecruiser** [comment]
Same issue: Grails 4.0.3, Tomcat 9.0.16, Ubuntu 18.04, JDK 1.8.201. Applied the trick 
compile "org.grails.plugins:cache", {exclude group: "org.codehaus.groovy", module: "groovy-all"}
and it runs well. 
According to the above comments, does it mean that Grails 4.0.4 doesn't have the issue?

**Comment by radutanasa** [comment]
I've just encountered this issue on OpenSuse 42.2 with Grails 4.0.4, Tomcat 9.0.37, JDK 1.8.

**Comment by andersonentwistle** [comment]
Can confirm the same. The proposed fix worked. Grails 4.0.4, Tomcat 9.0.39

**Comment by andersonentwistle** [comment]
# Methods
### Background
- `Linux work 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- [SDKMAN](https://sdkman.io/)'s Java and Grails binaries
- Java `11.0.9.open-adpt`

### Process
```shell
grails create-app test406
```

By the [docs](https://docs.grails.org/4.0.6/guide/deployment.html#deploymentContainer), change
```
compile "org.springframework.boot:spring-boot-starter-tomcat"
```
to
```
provided "org.springframework.boot:spring-boot-starter-tomcat"
```

Create a Dockerfile:
```
FROM tomcat:9.0.43-jdk11-openjdk-slim-buster

COPY build/libs/test406-0.1.war webapps/ROOT.war

```

Finally,
```bash
./gradlew assemble
docker build -t test406 .
docker run -it --rm -p 8080:8080 test406
```

# Results
| Java | Grails | Tomcat | Error | Workaround |
|-|-|-|-|-|
| 11.0.9.1 | 4.0.7 | 10.0.2 | 404 Not Found ||
||| 9.0.43 |||
|| 4.0.6 | 10.0.2 | 404 Not Found | &#x2717; |
||| 9.0.43 | Stack trace 1 | &#x2713; |

Note that the errors with just '404' had nothing that seemed to be thrown.

### Stack traces
#### 1
```
java.lang.IllegalStateException: Error starting child
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:720)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:706)
		at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:946)
		at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1792)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
		at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
		at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:757)
		at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:426)
		at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1520)
		at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309)
		at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
		at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
		at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:936)
		at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:843)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
		at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
		at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.StandardService.startInternal(StandardService.java:434)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.startup.Catalina.start(Catalina.java:772)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
		at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:342)
		at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:473)
	Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[]]
		at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:440)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:198)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:717)
		... 37 more
	Caused by: BUG! exception in phase 'semantic analysis' in source unit 'Script1.groovy' Cannot cast object 'io.micronaut.ast.groovy.utils.AstAnnotationUtils$_getAnnotationMetadata_closure1@6212232b' with class 'io.micronaut.ast.groovy.utils.AstAnnotationUtils$_getAnnotationMetadata_closure1' to class 'java.util.function.Function'
		at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:916)
		at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:574)
		at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:550)
		at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:527)
		at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:279)
		at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:258)
		at groovy.lang.GroovyShell.parseClass(GroovyShell.java:613)
		at groovy.lang.GroovyShell.parse(GroovyShell.java:625)
		at groovy.lang.GroovyShell.parse(GroovyShell.java:652)
		at groovy.lang.GroovyShell.parse(GroovyShell.java:643)
		at groovy.lang.GroovyShell$parse.call(Unknown Source)
		at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
		at ch.qos.logback.classic.gaffer.GafferConfigurator.run(GafferConfigurator.groovy:71)
		at ch.qos.logback.classic.gaffer.GafferConfigurator$run.callCurrent(Unknown Source)
		at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
		at ch.qos.logback.classic.gaffer.GafferConfigurator.run(GafferConfigurator.groovy:44)
		at ch.qos.logback.classic.gaffer.GafferUtil.runGafferConfiguratorOn(GafferUtil.java:43)
		at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:67)
		at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
		at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
		at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
		at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
		at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
		at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:417)
		at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:362)
		at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:155)
		at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:132)
		at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:273)
		at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:90)
		at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:172)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5166)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		... 38 more
	Caused by: org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'io.micronaut.ast.groovy.utils.AstAnnotationUtils$_getAnnotationMetadata_closure1@6212232b' with class 'io.micronaut.ast.groovy.utils.AstAnnotationUtils$_getAnnotationMetadata_closure1' to class 'java.util.function.Function'
		at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.castToType(DefaultTypeTransformation.java:360)
		at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.castToType(ScriptBytecodeAdapter.java:599)
		at io.micronaut.ast.groovy.utils.AstAnnotationUtils.getAnnotationMetadata(AstAnnotationUtils.groovy:53)
		at io.micronaut.ast.groovy.TypeElementVisitorTransform.visit(TypeElementVisitorTransform.groovy:83)
		at org.codehaus.groovy.transform.ASTTransformationVisitor$3.call(ASTTransformationVisitor.java:319)
		at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:912)
		... 73 more
```

**Comment by jdaugherty** [comment]
Micronaut has been removed from later versions of Grails by default.  I also know that @jamesfredley uses Tomcat to deploy Grails 7 applications.  I'm closing this and we can reopen if it's still an issue in Grails 7.
